{
 "title": "Grafana Dashboard for NetApp ONTAP v9.8+",
 "description": "Grafana Dashboard for NetApp ONTAP v9.8+",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "15s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "clustername",
    "label": "Cluster Name",
    "query": "SHOW TAG VALUES FROM netapp_cluster_overview WITH KEY=clustername"
   },
   {
    "name": "aggregate",
    "label": "Aggregate Name",
    "query": "SHOW TAG VALUES FROM netapp_aggregate_overview WITH KEY=aggregateName"
   },
   {
    "name": "svm",
    "label": "SVM Name",
    "query": "SHOW TAG VALUES FROM netapp_SVM_overview WITH KEY=SVMName"
   },
   {
    "name": "volume",
    "label": "Volume Name",
    "query": "SHOW TAG VALUES FROM netapp_volumes_overview WITH KEY=volumeName"
   },
   {
    "name": "share",
    "label": "Share Name",
    "query": "SHOW TAG VALUES FROM netapp_shares_overview WITH KEY=shareName"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.veeam.com/backup-azure.html\" target=\"_blank\"><img src=\"https://www.mysmartgroup.co.uk/wp-content/uploads/2017/12/NetApp-logo.png\" alt=\"NetApp-logo\" width=\"100%\"/></a>\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cluster Name: $tag_clustername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_overview",
     "select": [
      [
       { "params": [ "versiongeneration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "OS version: $tag_clusterversion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clusterversion" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_overview",
     "select": [
      [
       { "params": [ "versiongeneration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "MGM Network: $tag_managementnetwork",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "managementnetwork" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_overview",
     "select": [
      [
       { "params": [ "versiongeneration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "clustername" },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Latency Other",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "latencyOther" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "Latency Read",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "latencyRead" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "Latency Write",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "latencyWrite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "Latency Total",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "latencyTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Capacity - $aggregate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netapp_aggregate_overview",
     "query": "SELECT last(\"efficiencylogical\") FROM \"netapp_aggregate_overview\" WHERE (\"clustername\" =~ /^$clustername$/ AND \"aggregateName\" =~ /^$aggregate$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "efficiencylogical" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "aggregateName", "operator": "=~", "value": "/^$aggregate$/" }
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netapp_aggregate_overview",
     "select": [
      [
       { "params": [ "spaceblockstorageavailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "aggregateName", "operator": "=~", "value": "/^$aggregate$/" }
     ]
    },
    {
     "alias": "Data Reduction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netapp_aggregate_overview",
     "select": [
      [
       { "params": [ "efficencyratio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "aggregateName", "operator": "=~", "value": "/^$aggregate$/" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"efficiencylogical\") * (100 / last(\"spaceblockstorageavailable\"))  FROM \"netapp_aggregate_overview\" WHERE (\"clustername\" =~ /^$clustername$/ AND \"aggregateName\" =~ /^$aggregate$/) AND $timeFilter GROUP BY time($inter) , \"source\"  fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage VMs",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMNFS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NFS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMCIFS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CIFS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMISCSI" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "iSCSI" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMFCP" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FCP" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMNVME" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NVMe" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMS3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "S3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" }
     ],
     "measurement": "netapp_SVM_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "SVMSnapMirror" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SnapMirror" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" },
      { "params": [ "volumeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_volumes_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "volumeAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "SVMName", "operator": "=~", "value": "/^$svm$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "volumeName" ], "type": "tag" },
      { "params": [ "volumestyle" ], "type": "tag" },
      { "params": [ "volumestate" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_volumes_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "volumesize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "SVMName", "operator": "=~", "value": "/^$svm$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "IOPS Other",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "iopsOther" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "IOPS Read",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "iopsRead" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "IOPS Write",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "iopsWrite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "IOPS Total",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "iopsTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "LUN",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" },
      { "params": [ "LUNName" ], "type": "tag" },
      { "params": [ "LUNOSType" ], "type": "tag" },
      { "params": [ "LUNstate" ], "type": "tag" },
      { "params": [ "LUNlocation" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_LUN_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "LUNSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "SVMName", "operator": "=~", "value": "/^$svm$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" },
      { "params": [ "LUNName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_LUN_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "LUNUsed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "SVMName", "operator": "=~", "value": "/^$svm$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Throughput Other",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "troughputOther" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "Throughput Read",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "troughputRead" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "Throughput Write",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "troughputWrite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "Throughput Total",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_cluster_metrics",
     "select": [
      [
       { "params": [ "troughputTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Shares",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "SVMName" ], "type": "tag" },
      { "params": [ "shareName" ], "type": "tag" },
      { "params": [ "sharePath" ], "type": "tag" },
      { "params": [ "volumeName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "netapp_shares_overview",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "shareEncryption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "SVMName", "operator": "=~", "value": "/^$svm$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 22 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}